version: '3.9'

services:
    postgres:
        image: postgres
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
    jaeger:
        image: jaegertracing/all-in-one:latest
        environment:
            - COLLECTOR_ZIPKIN_HTTP_PORT=9411
        ports:
            - '5775:5775/udp'
            - '6831:6831/udp'
            - '6832:6832/udp'
            - '5778:5778'
            - '16686:16686'
            - '14268:14268'
            - '14250:14250'
            - '9411:9411'
    redis:
        image: redis
        expose: [6379]
        ports: ['6379:6379']
